### PR TITLE
promised pull request that fixed my windows installation problems

### PR DESCRIPTION
**Pull request by marsmensch**
added basic auth parameter for winrm client to fix installation, tested with both windows installation types

### CODE REVIEW

**Comment by jedi4ever** [comment]
hey @marsmensch could you send the pull request to veewee ? Also encrypting the password is not a good thing I think.

**Comment by marsmensch** [comment]
Yes, that was the first thing planned for tomorrow.

What is the problem with the encrypted password? I did not touch any other
options.

Am 24.01.2013 um 13:23 schrieb Patrick Debois notifications@github.com:

hey @marsmensch https://github.com/marsmensch could you send the pull
request to veewee ? Also encrypting the password is not a good thing I
think.

—
Reply to this email directly or view it on
GitHubhttps://github.com/hh/windows-fromscratch/pull/2#issuecomment-12648809.

**Comment by hh** [comment]
Thanks for squashing that bug @marsmench !

I think you made you changes against an earlier release, when I was using encrypted pass. Using a non-encrypted version makes it easier to understand and make changes etc.

**Comment by hh** [comment]
https://github.com/hh/windows-fromscratch/commit/4a497f39b reverting to plain text passwords.

**Comment by marsmensch** [comment]
You are welcome! I thought i synced with your master before branching, but
i guess i messed it up doing it in a hurry.

Will have a look at it tomorrow and also create a pull request for
upstream/veewee.

Thanks for your work!

Am 24.01.2013 um 17:27 schrieb Hippie Hacker notifications@github.com:

Thanks for squashing that bug @marsmench !

I think you made you changes against an earlier release, when I was using
encrypted pass. Using a non-encrypted version makes it easier to understand
and make changes etc.

—
Reply to this email directly or view it on
GitHubhttps://github.com/hh/windows-fromscratch/pull/2#issuecomment-12659348.

**Pull request merged**
